# Generated by Django 4.1.3 on 2022-11-21 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_user', models.BooleanField(default=False, verbose_name='User already booked a trial')),
                ('booked_site', models.CharField(default='', max_length=32, verbose_name='Booking Sites Available')),
                ('booked_date', models.DateField(default=django.utils.timezone.now, verbose_name='Booking Dates Available')),
                ('booked_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Booking Time Available')),
                ('trial_status', models.CharField(choices=[('Not_Taken', 'Not_Taken'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Not_Taken', max_length=32, verbose_name='Trial Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
