# Generated by Django 4.1.3 on 2022-11-25 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_status', models.CharField(choices=[('Pending Trial', 'Pending Trial'), ('In process of printing Card', 'In process of printing Card'), ('In delivery process ', 'In delivery process')], default='Pending Trial', max_length=32, verbose_name='License Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_user', models.BooleanField(default=False, verbose_name='Booked trial')),
                ('booked_site', models.CharField(default='', max_length=32, verbose_name='Booking Site')),
                ('booked_date', models.DateField(default=django.utils.timezone.now, verbose_name='Booking Date')),
                ('booked_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Booking Time')),
                ('trial_status', models.CharField(choices=[('Not Taken', 'Not Taken'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Not Taken', max_length=32, verbose_name='Trial Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
