# Generated by Django 4.1.3 on 2022-11-19 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_site', models.CharField(choices=[('site1', 'Sydney'), ('site2', 'Melbourne'), ('site3', 'Adelaide')], default='Sydney', max_length=32, verbose_name='Booking Site Available')),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Booking Dates Available')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
