# Generated by Django 4.1.3 on 2022-11-18 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='applicant_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Booking Dates Available'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_site',
            field=models.CharField(choices=[('site1', 'Sydney'), ('site2', 'Melbourne'), ('site3', 'Adelaide')], default='Sydney', max_length=32, verbose_name='Booking Site Available'),
        ),
    ]
