# Generated by Django 4.1.3 on 2022-11-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20221117_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
